on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        host: ${{ secrets.SONAR_TOKEN }}
        login: ${{ secrets.SONAR_HOST_URL }}
